version: 2.1

orbs:
  python: circleci/python@1.3.2

executors:
  default:
    machine:
      image: ubuntu-2004:202010-01
  
jobs:
  test:
    executor: default
    steps:
      - run:
          name: Install dotnet 
          command: |
              # install dotnet https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2010-
              wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
              sudo dpkg -i packages-microsoft-prod.deb
              sudo apt-get update
              sudo apt-get install -y apt-transport-https
              sudo apt-get install -y dotnet-sdk-3.1
      - run:
          name: install iqsharp
          command: |
              dotnet iqsharp install --user

      - python/test:
          args: '-E qcware-quasar -E qiskit -E pyzx -E braket -E qsharp'
          pkg-manager: poetry
          test-tool: pytest

workflows:
  main:
    jobs:
      - test

            
      
