version: 2.1

orbs:
  python: circleci/python@1.3.2

workflows:
  main:
    jobs:
      - python/test:
          args: '-E qcware-quasar -E qiskit -E pyzx -E braket -E qsharp'
          pkg-manager: poetry
          test-tool: pytest
