version: 2.1

orbs:
  python: circleci/python@1.4.0

executors:
  qsharp:
    docker:
      - image: vputz/cimg_python_qsharp

workflows:
  main:
    jobs:
      - python/test:
          executor: qsharp
          args: '-E qcware-quasar -E qiskit -E pyzx -E braket -E qsharp'
          pkg-manager: poetry
          test-tool: pytest
